# Generated by Django 5.0.7 on 2024-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='sale_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
