# Generated by Django 5.0.7 on 2024-11-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_purchase_sale_date_alter_purchase_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='sale_date',
        ),
    ]
